# Generated by Django 3.1.7 on 2021-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiqlimapp', '0002_auto_20210313_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramweb',
            name='idioma',
            field=models.CharField(choices=[('es-EU', 'Español-Europa'), ('en-EN', 'English-England')], help_text='Idioma de la web', max_length=5),
        ),
    ]
