# Generated by Django 3.1.7 on 2021-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webiqlimapp', '0003_auto_20210313_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramweb',
            name='imagen',
            field=models.ImageField(upload_to='webiqlimapp'),
        ),
    ]
