# Generated by Django 3.1.7 on 2021-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(help_text='Título del Post', max_length=50),
        ),
    ]
