# Generated by Django 3.1.7 on 2021-03-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20210304_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['ordenaparicion'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='ordenaparicion',
            field=models.IntegerField(default=1, help_text='Orden de aparición en la web', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(help_text='Título del Servicio', max_length=50),
        ),
    ]
