# Generated by Django 3.1.7 on 2021-03-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20210307_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='efecto',
            field=models.CharField(choices=[('P', 'Pequena'), ('M', 'Mediana')], default='P', help_text='Efecto de la imagen', max_length=1),
        ),
        migrations.AddField(
            model_name='servicio',
            name='eslogo',
            field=models.BooleanField(default=False),
        ),
    ]
