# Generated by Django 3.1.7 on 2021-03-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20210313_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='eslogo',
            field=models.BooleanField(default=False, help_text='Si es logo no redirecciona a texto servicio'),
        ),
    ]
