# Generated by Django 3.1.7 on 2021-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20210313_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='formato',
            field=models.CharField(choices=[('C', 'Circular'), ('N', 'Normal')], default='N', help_text='Aparecera la imagen en cirulo o cuadrada-Normal', max_length=1),
        ),
    ]
