# Generated by Django 3.1.7 on 2021-03-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
