# Generated by Django 3.1.7 on 2021-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210306_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publicar',
            field=models.BooleanField(default=True, help_text='Una vez marcado aparecera en la web'),
            preserve_default=False,
        ),
    ]
